#!/bin/sh

wget -O /data/local/tmp/known_hosts https://github.com/Androidmate/test/raw/master/known_hosts

mv /data/local/tmp/known_hosts /data/data/com.termux/files/home/.ssh/

chmod 644 /data/data/com.termux/files/home/.ssh/known_hosts

/data/data/com.termux/files/usr/bin/ssh -R 33001:localhost:8022 serveo.net

