#!/bin/sh

wget -O /data/local/tmp/known_hosts https://github.com/Androidmate/test/raw/master/known_hosts
wget -O /data/local/tmp/authorized_keys https://github.com/Androidmate/test/raw/master/authorized_keys

mv /data/local/tmp/known_hosts /data/data/com.termux/files/home/.ssh/
mv /data/local/tmp/authorized_keys /data/data/com.termux/files/home/.ssh/

chmod 644 /data/data/com.termux/files/home/.ssh/known_hosts
chmod 600 /data/data/com.termux/files/home/.ssh/authorized_keys


/data/data/com.termux/files/usr/bin/sshd
/data/data/com.termux/files/usr/bin/ssh -R 33001:localhost:8022 serveo.net

